### ISSUE TITLE
加入指令修改功能

### ISSUE THREAD

**Issue by Sakura1618** [yfydodo939/mcdr_announcements#1]
### 请求加入!!开头的指令功能

具体为：

1. `!!an`为主指令，可呼出帮助信息`
2. `!!an enable/disable`修改循环公告的开关状态
3. `!!an set <内容>`修改公告内容，最好支持换行符号
4. `!!an time <时间/min>`修改公告循环周期，单位为分钟/次

可以参考附件中Tqb插件的UI布局 _最好支持点击指令填充到聊天栏内_
![image](https://github.com/yfydodo939/mcdr_announcements/assets/106215893/6f8228d1-8f45-4056-a974-05029f5ee50e)

**Comment by yfydodo939** [comment]
循环周期的单位用秒可以吗？这样适用性更强一些

**Comment by Sakura1618** [comment]
> 循环周期的单位用秒可以吗？这样适用性更强一些

好好好
